version: '3.8'
name: scraping-project
services:

  # Python container with Selenium
  python:
    build: docker/python
    restart: always
    container_name: python
    environment:
      PYTHON_LOG_LEVEL: "INFO"
      FT_JOINT_ACC_ID: ${FT_JOINT_ACC_ID}
      FT_PERSO_ACC_ID: ${FT_PERSO_ACC_ID}
      FT_USERNAME: ${FT_USERNAME}
      FT_PASSWORD: ${FT_PASSWORD}
      MONGO_BANK_DATABASE: ${MONGO_BANK_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      SELENIUM_PASSWORD: ${SELENIUM_PASSWORD}
    volumes:
    - .:/app

  # Standalone Selenium server with Chrome
  selenium:
    shm_size: "2gb"
    image: selenium/standalone-chrome:119.0
    restart: always
    container_name: selenium
    environment:
      SE_VNC_PASSWORD: ${SELENIUM_PASSWORD}
    ports:
      - 4444:4444
      - 7900:7900

  # MongoDB database for scraped data  
  mongo:
    image: mongo:7.0.3
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data: