version: '3.8'
name: scraping-project
services:

  # Python container with Selenium
  python:
    image: ghcr.io/aandriano931/polyvalent-scraper:latest
    restart: always
    container_name: python
    environment:
      PYTHON_LOG_LEVEL: "INFO"
      FT_JOINT_ACC_ID: ${FT_JOINT_ACC_ID}
      FT_PERSO_ACC_ID: ${FT_PERSO_ACC_ID}
      FT_USERNAME: ${FT_USERNAME}
      FT_PASSWORD: ${FT_PASSWORD}
      FT_ENTRYPOINT_URL: ${FT_ENTRYPOINT_URL}
      FT_JOINT_HISTORY_FILE_PATH: ${FT_JOINT_HISTORY_FILE_PATH}
      FT_PERSONAL_HISTORY_FILE_PATH: ${FT_PERSONAL_HISTORY_FILE_PATH}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SELENIUM_PASSWORD: ${SELENIUM_PASSWORD}
      ENABLE_MAIL: ${ENABLE_MAIL}
      MAIL_RECIPIENT: ${MAIL_RECIPIENT}
      MAIL_SENDER: ${MAIL_SENDER}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      LOG_DIR: ${LOG_DIR}
    networks:
      - home-hub_net
    volumes:
      - .:/app
      - ${LOG_DIR}:/var/log

  # Standalone Selenium server with Chrome
  selenium:
    shm_size: "2gb"
    image: selenium/standalone-chrome:119.0
    restart: always
    container_name: selenium
    environment:
      SE_VNC_PASSWORD: ${SELENIUM_PASSWORD}
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - home-hub_net

networks:
  home-hub_net:
    external: true