version: '3.8'
name: scraping-project
services:

  # Python container with Selenium
  python:
    build: docker/python
    restart: always
    container_name: python
    environment:
      PYTHON_LOG_LEVEL: "INFO"
      FT_JOINT_ACC_ID: ${FT_JOINT_ACC_ID}
      FT_PERSO_ACC_ID: ${FT_PERSO_ACC_ID}
      FT_USERNAME: ${FT_USERNAME}
      FT_PASSWORD: ${FT_PASSWORD}
      MONGO_BANK_DATABASE: ${MONGO_BANK_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SELENIUM_PASSWORD: ${SELENIUM_PASSWORD}
    volumes:
    - .:/app

  # Standalone Selenium server with Chrome
  selenium:
    shm_size: "2gb"
    image: selenium/standalone-chrome:119.0
    restart: always
    container_name: selenium
    environment:
      SE_VNC_PASSWORD: ${SELENIUM_PASSWORD}
    ports:
      - 4444:4444
      - 7900:7900

  # MongoDB database for scraped data  
  # mongo:
  #   image: mongo:7.0.3
  #   restart: always
  #   container_name: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo-data:/data/db

  # MySQL Database
  mysql:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: home-hub
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Europe/Paris'
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  # phpmyadmin GUI for mysql     
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    container_name: phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

volumes:
  mongo-data:
  mysql-data: