name: Deploy Polyvalent Scraper

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'v*'
  workflow_run:
    workflows: [build]
    types: [completed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy code and rebuild containers
    runs-on: ubuntu-latest

    steps:
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Push code to server
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
        cd ${{ secrets.WORK_DIR }} &&
        git checkout ${{ secrets.MAIN_BRANCH }} &&
        git pull"

    - name: Upload .env to server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cat > ${{ secrets.WORK_DIR }}/.env' <<EOF
        SELENIUM_PASSWORD=${{ secrets.SELENIUM_PASSWORD }}
        FT_ENTRYPOINT_URL=${{ secrets.FT_ENTRYPOINT_URL }}
        FT_USERNAME=${{ secrets.FT_USERNAME }}
        FT_PASSWORD=${{ secrets.FT_PASSWORD }}
        FT_JOINT_ACC_ID=${{ secrets.FT_JOINT_ACC_ID }}
        FT_PERSO_ACC_ID=${{ secrets.FT_PERSO_ACC_ID }}
        MYSQL_USER=${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        MONGODB_USER=${{ secrets.MONGODB_USER }}
        MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
        MAIL_RECIPIENT=${{ secrets.MAIL_RECIPIENT }}
        MAIL_SENDER=${{ secrets.MAIL_SENDER }}
        SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
        SMTP_SERVER=${{ secrets.SMTP_SERVER }}
        EOF

    - name: Build and start containers
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
        cd ${{ secrets.WORK_DIR }} &&
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin &&
        docker compose --env-file .env up -d"

    # - name: Clean up .env from server
    #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -f ${{ secrets.WORK_DIR }}/.env"

    - name: Cleanup local SSH
      run: rm -rf ~/.ssh